apiVersion: v1
kind: Namespace
metadata:
  name: volcano-system
  labels:
    kubernetes.io/metadata.name: volcano-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: podsecuritypolicy
  namespace: volcano-system
rules:
- apiGroups:
  - policy
  - extensions
  resourceNames:
  - system
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podsecuritypolicy
  namespace: volcano-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: podsecuritypolicy
subjects:
- kind: ServiceAccount
  name: default
- kind: ServiceAccount
  name: volcano-controllers
- kind: ServiceAccount
  name: volcano-scheduler
- kind: ServiceAccount
  name: volcano-admission
