apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: kueue-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: podsecuritypolicy
  namespace: kueue-system
rules:
- apiGroups:
  - policy
  - extensions
  resourceNames:
  - system
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podsecuritypolicy
  namespace: kueue-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: podsecuritypolicy
subjects:
- kind: ServiceAccount
  name: default
- kind: ServiceAccount
  name: kueue-controller-manager
